version: '3'
services:
  db:
    image: postgres:16
    restart: always
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
    container_name: db-planilla
    volumes:
      - ./postgres-data:/var/lib/postgresql/data