import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../styles/globals.css";
import { CircleInit } from "@/shared/icons/CircleInit";
import { Menu } from "./Menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} min-h-screen flex custom-scrollbar `}
      >
        <div className="flex flex-col  w-40 bg-gray-800">
          <header className="p-4 fixed top-0 w-40 min-h-screen max-h-full overflow-y-auto">
            <div className="col-span-1 bg-[#1E293B]">
              <div className="m-4">
                <CircleInit />
              </div>
              <p className="text-center">Sistema RRHH</p>
            </div>
            {/* <Menu /> */}
          </header>
        </div>
        <main className="flex-1 text-white p-4">{children}</main>
        <footer></footer>
      </body>
    </html>
  );
}
